scenable/events/urls.py
from django.conf.urls import patterns, url
from scenable.events.views import PageEventsFeed

from haystack.views import search_view_factory

urlpatterns = patterns('scenable.events.views',
    url(r'^$', search_view_factory(view_class=PageEventsFeed), name='events-feed'),
    url(r'^(?P<eid>\d+)/$', 'page_details', name='event-detail'),
)

urlpatterns += patterns('scenable.events.ajax',
    url(r'^ajax/attend/$', 'event_attend'),
)

scenable/news/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('scenable.news.views',
    url(r'^$', 'page_feed', name='news-feed'),
)

scenable/tags/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('scenable.tags.views',
    url(r'^(?P<tid>\d+)/$', 'detail_page', name='tag-detail'),
)

scenable/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic.simple import redirect_to, direct_to_template

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

from haystack.forms import SearchForm
from haystack.views import search_view_factory
from scenable.common.views import PageSiteSearch
from scenable import settings

from tastypie.api import Api
from scenable.places.api import PlaceResource
from scenable.places.api import CategoryResource as PlaceCategoryResource
from scenable.events.api import EventResource
from scenable.events.api import CategoryResource as EventCategoryResource
from scenable.specials.api import SpecialResource
from scenable.news.api import NewsResource
from scenable.now.api import NoticeResource, FeaturedImageResource

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'scenable.common.views.page_home', name='home'),

    # system admin and business admin pages
    url(r'^djadmin/', include(admin.site.urls)),
    url(r'^manage/', include('scenable.orgadmin.urls')),

    # QR-code redirect handling
    url(r'^qr/$', 'scenable.common.views.qr_redirect'),
    url(r'^qr$', 'scenable.common.views.qr_redirect'),
    url(r'^qr/(\w+)/$', 'scenable.common.views.qr_redirect'),
    url(r'^qr/(\w+)$', 'scenable.common.views.qr_redirect'),

    # Scenable and Oakland shirt QRs
    url(r'^mobile-about/$', direct_to_template, {'template': 'qr/mobile_about.html'}, name='mobile-about'),
    url(r'^oakland-teaser/$', direct_to_template, {'template': 'qr/oakland_teaser.html'}, name='oakland-teaser'),

    # Static about pages for scenable.com.
    url(r'^about/$', redirect_to, {'url': '/'}, name='about'),
    url(r'^about-oakland/$', 'scenable.common.views.page_static_about_oakland', name='about-oakland'),
    url(r'^app/$', 'scenable.common.views.page_static_download_app', name='download-app'),
    url(r'^team/$', 'scenable.common.views.page_static_team', name='team'),
    url(r'^mission/$', 'scenable.common.views.page_static_mission', name='mission'),

    # Error pages
    url(r'^500\.html$', direct_to_template, {'template': '500.html'}, name='500'),
    url(r'^404\.html$', direct_to_template, {'template': '404.html'}, name='404'),
    url(r'^403\.html$', direct_to_template, {'template': '403.html'}, name='403'),

    ### TEMPORARILY REDIRECT LOGIN/SIGNUP URLS TO HOME PAGE ###
    url(r'^login/$', 'scenable.common.views.page_home', name='login'),
    url(r'^signup/$', 'scenable.common.views.page_home', name='signup'),

    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout', kwargs={'next_page': '/login/'}),

    url(r'^accounts/', include('scenable.accounts.urls')),

    #### OAKLAND CONTENT SPECIFIC URLs

    url(r'^oakland/$', 'scenable.common.views.page_oakland_home', name='beta-home'),

    url(r'^oakland/places/', include('scenable.places.urls')),
    url(r'^oakland/events/', include('scenable.events.urls')),
    url(r'^oakland/specials/', include('scenable.specials.urls')),
    url(r'^oakland/news/', include('scenable.news.urls')),
    url(r'^oakland/chatter/', include('scenable.chatter.urls')),
    url(r'^oakland/now/$', 'scenable.now.views.page_now', name='now'),

    url(r'^oakland/tags/', include('scenable.tags.urls')),

    url(r'^oakland/search/', search_view_factory(
        view_class=PageSiteSearch,
        template='search/page_site_search.html',
        form_class=SearchForm
    ), name='site-search'),
)

### TEMPORARY DISABLED MISC. UNNAMED URLS ####
#     # feedback form
#     url(r'^feedback/ajax/generic/$', 'scenable.feedback.ajax.submit_generic'),

# API setup
v1_api = Api(api_name='v1')
v1_api.register(PlaceResource())
v1_api.register(PlaceCategoryResource())
v1_api.register(EventResource())
v1_api.register(EventCategoryResource())
v1_api.register(SpecialResource())
v1_api.register(NewsResource())
v1_api.register(NoticeResource())
v1_api.register(FeaturedImageResource())

urlpatterns += patterns('',
    (r'^api/', include(v1_api.urls)),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scenable/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from scenable.common.core.viewmodels import ViewModel
from scenable.places.models import Place


class BetaMember(models.Model):
    email = models.EmailField()

    def save(self, *args, **kwargs):
        self.email = self.email.lower()
        super(BetaMember, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.email


class UserProfile(models.Model, ViewModel):
    '''
    Extended information for any user of the site.
    '''
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )

    user = models.OneToOneField(User)
    display_name = models.CharField(max_length=30, blank=True)

    avatar = models.ImageField(upload_to='img/a', null=True, blank=True)
    points = models.IntegerField(default=0)

    # all of the following should be optional on a registration form
    fb_id = models.CharField(max_length=50, blank=True)
    fb_id_public = models.BooleanField(default=True)

    twitter_username = models.CharField(max_length=15, blank=True)
    twitter_username_public = models.BooleanField(default=True)

    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)
    birth_date = models.DateField(null=True, blank=True)

    neighborhood = models.CharField(max_length=50, blank=True)

    # temporary location for these settings. when they're more complcated, they'll have their own model setup
    public_favorites = models.BooleanField(default=True)
    public_attendance = models.BooleanField(default=False)
    public_coupons = models.BooleanField(default=True)

    def __unicode__(self):
        return unicode(self.user)

    def to_data(self, *args, **kwargs):
        '''
        Manually choose and insert user information. Note that
        two ids are produced in the data output: id (User.id)
        and profile_id (UserProfile.id).
        '''
        data = super(UserProfile, self).to_data(*args, **kwargs)
        data['profile_id'] = self.id
        data.pop('user_id')
        user_fields = ('id', 'username', 'email')
        for k in user_fields:
            data[k] = getattr(self.user, k)
        return data

    def display_or_username(self):
        return self.display_name if self.display_name else self.user.username


class Organization(models.Model):
    '''
    Represents organizations in the community (business, charity, etc.)
    '''
    name = models.CharField(u'Organization name', max_length=200)
    dtcreated = models.DateTimeField(u'Datetime created', auto_now_add=True)

    administrators = models.ManyToManyField(User, verbose_name=u'Users with administrator access',
        blank=True, null=True)
    establishments = models.ManyToManyField(Place, verbose_name=u'Establishments owned',
        blank=True, null=True)

    image = models.ImageField(upload_to='img/o', null=True, blank=True)
    url = models.URLField('Website', blank=True)
    fb_id = models.CharField('Facebook ID', max_length=50, blank=True)
    twitter_username = models.CharField(u'Twitter username', max_length=15, blank=True)

    def __unicode__(self):
        return self.name


# signal handler to automatically create a new UserProfile
def create_user_profile(sender, instance, created, **kwargs):
    # raw will be true when loaddata script is run (will run
    # into a db uniqueness conflict if we have a fixture that
    # tried to load corresponding profiles)
    if created and not kwargs.get('raw', False):
        UserProfile.objects.create(user=instance)
post_save.connect(create_user_profile, sender=User)

scenable/chatter/models.py
from django.db import models

from django.contrib.auth.models import User
from django.template.defaultfilters import truncatechars


class Post(models.Model):
    dtcreated = models.DateTimeField(auto_now_add=True)
    content = models.CharField(max_length=140)
    author = models.ForeignKey(User)

    def __unicode__(self):
        return '"%s" by %s' % (truncatechars(self.content, 15), self.author.username)

scenable/orgadmin/models.py
from django.db import models

# Create your models here.

scenable/outsourcing/apitools/models.py
from django.db import models
# dummy file needed for django

scenable/testbed/models.py
from django.db import models

# Create your models here.

scenable/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from scenable.accounts.models import UserProfile, BetaMember, Organization

from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate


class EmailAuthenticationForm(AuthenticationForm):
    '''
    AuthenticationForm that accepts an email address as well as a username.
    '''
    def clean(self):
        '''
        Override default logging in behavior to allow for email address
        login. Doing this here instead of clean_username because we don't
        want to reveal email addresses via a field-specific error message.
        '''
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            if '@' in username:
                # grab all possible usernames associated with this email address to authenitcate with
                # we'll never allow a login for more than one, but trying all of them allows us to
                # hold off on the multi-user email error until after a good password is used
                usernames = [u.username for u in User.objects.filter(email=username)]
                auth_users = [authenticate(username=username, password=password) for username in usernames]
                if not any(auth_users):
                    raise forms.ValidationError("Please enter a correct email address and password. Note that both fields are case-sensitive.")
                if len(auth_users) > 1:
                    raise forms.ValidationError("This email address is associated with more than one user. Please use a username.")
                self.user_cache = auth_users[0]
            else:
                # standard authentication
                self.user_cache = authenticate(username=username, password=password)
                if self.user_cache is None:
                    raise forms.ValidationError("Please enter a correct username and password. Note that both fields are case-sensitive.")
                elif not self.user_cache.is_active:
                    raise forms.ValidationError("This account is inactive.")
        self.check_for_test_cookie()
        return self.cleaned_data


class RememberMeForm(forms.Form):
    '''
    Basic checkbox for remembering the user. Responsibility of the view to
    do something with this value.
    '''
    remember_me = forms.BooleanField(label="Keep me logged in on this computer", initial=False)


class RegistrationForm(UserCreationForm):
    '''
    Overrides UserCreationForm to include email address, also disallows @
    symbols in usernames.
    '''
    username = forms.RegexField(label="Username", max_length=30, regex=r'^[\w.+-]+$',
        help_text="Required. 30 characters or fewer. Letters, digits and ./+/-/_ only.",
        error_messages={'invalid': "This value may contain only letters, numbers and ./+/-/_ characters."})
    email = forms.EmailField(label="Email address", required=True)

    class Meta(UserCreationForm.Meta):
        fields = ("username", "email",)

    def save(self, commit=True):
        '''
        Adds email to saved user.
        '''
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class EmailForm(forms.ModelForm):
    """
    A form for changing a user's email. Note that this form mandates that a
    user has an email address.
    """
    # same as default field, but with required turned off
    email = forms.EmailField(max_length=75, required=True, label=u'E-mail address')

    class Meta:
        model = User
        fields = ("email",)


class BetaRegistrationForm(RegistrationForm):
    '''
    Special registration form for the private beta. Only allows users with
    email addresses in a BetaMember object to register.
    '''
    def clean_email(self):
        email = self.cleaned_data['email'].strip().lower()
        if BetaMember.objects.filter(email=email).count() < 1:
            raise forms.ValidationError('This email address is not registered for entry into the Scenable private beta launch. '\
                                  'Are you sure you used the email address we have on record?')
        try:
            existing_user = User.objects.get(email=email)
            if existing_user.organization_set.count() > 0:
                raise forms.ValidationError('An business account for this email address already exists. Go ahead to the login page to enter the site.')
        except User.DoesNotExist:
            return email


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ('user', 'points')

    birth_date = forms.DateField(label=u'Birth date',
        widget=forms.DateInput(format='%m/%d/%Y'),
        input_formats=('%m/%d/%Y', '%m/%d/%y',),
        required=False)


class ActivityPreferencesForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('public_favorites', 'public_attendance', 'public_coupons')


class CredentialsForm(PasswordChangeForm):
    email = forms.EmailField(label=u'Email address')

    def __init__(self, user, *args, **kwargs):
        initial = kwargs.setdefault('initial', {})
        if 'email' not in initial:
            initial['email'] = user.email
        super(CredentialsForm, self).__init__(user, *args, **kwargs)

    def save(self, commit=True):
        # parent sets the new password
        super(CredentialsForm, self).save(commit=False)
        self.user.email = self.cleaned_data['email']
        if commit:
            self.user.save()
        return self.user
CredentialsForm.base_fields.keyOrder = ['email', 'old_password',
                                        'new_password1', 'new_password2']


class OrganizationForm(forms.ModelForm):
    '''
    Organization-backed model form. Only exposes organization name.
    '''
    class Meta:
        model = Organization

scenable/chatter/forms.py
from django import forms
from scenable.chatter.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('content',)

    def __init__(self, author, *args, **kwargs):
        self.author = author
        super(PostForm, self).__init__(*args, **kwargs)

    def clean(self):
        if not self.author or not self.author.is_authenticated():
            raise forms.ValidationError('User must be logged in to post.')
        return super(PostForm, self).clean()

    def save(self, commit=True, *args, **kwargs):
        post = super(PostForm, self).save(commit=False, *args, **kwargs)
        post.author = self.author
        if commit:
            post.save()
        return post

scenable/common/forms.py
from django import forms
from haystack.forms import SearchForm


class CategorySearchForm(SearchForm):
    def __init__(self, choices, *args, **kwargs):
        super(CategorySearchForm, self).__init__(*args, **kwargs)
        self.fields['category'] = forms.ChoiceField(choices=choices, required=False)

scenable/events/forms.py
from django import forms

from scenable.events.models import Event


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        exclude = ('dtcreated', 'dtmodified',)

scenable/feedback/forms.py
from django import forms

from scenable.feedback.models import GenericFeedbackComment


class GenericFeedbackForm(forms.ModelForm):
    class Meta:
        model = GenericFeedbackComment
        fields = ('feedback',)

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(GenericFeedbackForm, self).__init__(*args, **kwargs)

    def clean(self):
        if not self.user or not self.user.is_authenticated():
            raise forms.ValidationError('User must be logged in to comment.')
        return super(GenericFeedbackForm, self).clean()

    def save(self, commit=True, *args, **kwargs):
        comment = super(GenericFeedbackForm, self).save(commit=False, *args, **kwargs)
        comment.user = self.user
        if commit:
            comment.save()
        return comment

scenable/places/forms.py
from django import forms

from scenable.places.models import Place, Location


class PlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        exclude = ('dtcreated',)


class LocationForm(forms.ModelForm):
    class Meta:
        model = Location

scenable/templates/accounts/events.html
{% comment %}
Inner template to render a list of events the user is attending.

Context variables:
    [feed_items]:  list of EventData instances
{% endcomment %}

<h2 class="detail-section-title">My Events</h2>
{% if feed_items %}
	<ul class="feed my-feed events">
	    {% for item in feed_items %}
	        <li class="item">{% include "events/feed_item.html" with event=item %}</li>
	    {% endfor %}
	</ul>
{% else %}
	<section class="no-items">
    	<img src="{{STATIC_URL}}img/manage-events.png" alt="Calendar" />
    	{% if user == public_user %}
    	<p>You currently don't have any favorited events. Browse the Events Page or look for an Events tab on a place's page. Then go to the Event's page and choose Favorite under the thumbnail.</p> 
    	{% else %}
    	<p>No favorited events here!</p>
    	{% endif %}
    </section>
{% endif %}

scenable/templates/accounts/manage_account.html
{% comment %}
Inner template for an account/profile management form.
Context variables:
    account_forms:
        profile_form: form object
        credentials_form: form object
        preferences_form: form object    
{% endcomment %}

<h2 class="detail-section-title">{{user.username}}'s Account</h2>

{% with form=account_forms.profile_form %}
<form method="post" action="{% url account-manage uname=user.username %}#profile-form" enctype="multipart/form-data" id="profile-form">
{% csrf_token %}
<fieldset>
	<legend>Profile</legend>
	<p class="tip">This information will appear publicly on your profile.</p>
	<ul>
		<li class="field-container">
			<div class="field-label">
				{{form.display_name.label_tag}}
			</div>
			<div class="field">
				{{form.display_name}}
				<p class="tip">Leave blank to use your username.</p>
				{{form.display_name.errors}}
			</div>
		</li> <!-- display_name -->

		<li class="field-container">
			<div class="field-label">
				{{form.gender.label_tag}}
			</div>
			<div class="field grouped-field-row">
				<div>
					{{form.gender}}
				</div> <!-- gender -->
				<div>
					{{form.birth_date.label_tag}}
				</div>
				<div>
					{{form.birth_date}}
					{{form.birth_date.errors}}
					<p class="tip">MM/DD/YYYY</p>
				</div> <!-- birth_date -->
			</div>
		</li>  <!-- gender & birth_date -->
		
		<li class="field-container">
			<div class="field-label">
				{{form.neighborhood.label_tag}}
			</div>
			<div class="field">
				{{form.neighborhood}}
				{{forn.neighborhood.errors}}
			</div>
		</li> <!-- neighborhood -->
		
		<li class="field-container">
			<div class="field-label">
				{{form.avatar.label_tag}}
			</div>
			<div class="field">
				{{form.avatar}}
				{{form.avatar.errors}}
			</div>
		</li> <!-- avatar -->

		<li class="field-container">
			<div class="field-label">
				{{form.twitter_username.label_tag}}
			</div>
			<div class="field">
				<div class="social-input">
		        	{{form.twitter_username}}
		        	{{form.twitter_username.errors}}
		            <img src="{{STATIC_URL}}img/icons/twitter.png" alt="Twitter icon" />
		        </div>
			</div>	
		</li> <!-- twitter_username -->
	</ul>
</fieldset>
<input type="submit" value="Save Profile Changes" name="save_profile" class="right"/>
{% if form in forms_saved %}
	<p class="right success">Changes saved!</p>
{% endif %}

</form>
{% endwith %}

{% with form=account_forms.preferences_form %}
<form method="post" action="{% url account-manage uname=user.username %}#privacy-form" enctype="multipart/form-data" id="privacy-form">
{% csrf_token %}
<fieldset id="account-privacy">
	<legend>Privacy</legend>
	<p class="tip">By default, your public profile page will show the places you favorite and the coupons you have purchased. You can opt in to make your events public.</p>
	<ul>
		<li class="field-container">
			<div class="third">
				<label name="{{form.public_favorites.html_name}}" for="id_public_favorites">
					<img src="{{STATIC_URL}}img/manage-place.png" />
					<!-- <p>Favorite Places</p> -->
					<span class="check-value">Public</span>
				</label>
				{{form.public_favorites}}
				
			</div> <!-- public_favorites -->

			<div class="third">
				<label name="{{form.public_attendance.html_name}}" for="id_public_attendance">
					<img src="{{STATIC_URL}}img/manage-events.png" />
					<!-- <p>Events</p> -->
					<span class="check-value">Public</span>
				</label>
				{{form.public_attendance}}
				
			</div> <!-- public_attendance -->

			<div class="third">
				<label name="{{form.public_coupons.html_name}}" for="id_public_coupons">
					<img src="{{STATIC_URL}}img/manage-special.png" />
				<!-- 	<p>My Coupons</p> -->
				<span class="check-value">Public</span>
				</label>
				{{form.public_coupons}}
				
			</div> <!-- public_coupons -->
		</li>
	</ul>
</fieldset>
<input type="submit" value="Save Privacy Changes" name="save_preferences" class="right"/>
{% if form in forms_saved %}
	<p class="right success">Changes saved!</p>
{% endif %}
</form>
{% endwith %}

{% with form=account_forms.email_form %}
<form method="post" action="{% url account-manage uname=user.username %}#email-form" enctype="multipart/form-data" id="email-form">
{% csrf_token %}
<fieldset>
	<legend>Email</legend>
	<p class="tip">Change your email address here.</p>
	<ul>
		<li class="field-container">
			<div class="field-label">
				{{form.email.label_tag}}
			</div>
			<div class="field">
				{{form.email}}
				{{form.email.errors}}
			</div>
		</li> <!-- email -->
	</ul>
</fieldset>
<input type="submit" value="Change Email" name="save_email" class="right"/>
{% if form in forms_saved %}
	<p class="right success">Changes saved!</p>
{% endif %}
</form>
{% endwith %}

{% with form=account_forms.password_form %}
<form method="post" action="{% url account-manage uname=user.username %}#password-form" enctype="multipart/form-data" id="password-form">
{% csrf_token %}
<fieldset>
	<legend>Password</legend>
	<p class="tip">Change your password here.</p>
	<ul>
		<li class="field-container">
			<div class="field-label">
				{{form.old_password.label_tag}}
			</div>
			<div class="field">
				{{form.old_password}}
				{{form.old_password.errors}}
			</div>
		</li> <!-- old_password -->

		<li class="field-container">
			<div class="field-label">
				{{form.new_password1.label_tag}}
			</div>
			<div class="field">
				{{form.new_password1}}
				{{form.new_password1.errors}}
			</div>
		</li> <!-- new_password1 -->

		<li class="field-container">
			<div class="field-label">
				{{form.new_password2.label_tag}}
			</div>
			<div class="field">
				{{form.new_password2}}
				{{form.new_password2.errors}}
			</div>
		</li> <!-- new_password2 -->
	</ul>
</fieldset>
<input type="submit" value="Change Password" name="save_password" class="right"/>
{% if form in forms_saved %}
	<p class="right success">Changes saved!</p>
{% endif %}
</form>
{% endwith %}

scenable/templates/accounts/nav_tabs.html
{% comment %}
Inner template for nav panel

Context variables:
    public_user: User object
    current_panel: string
{% endcomment %}

{% with p=current_panel %}

<ul>
	{% if user == public_user %}
    <li><a href="{% url account-manage uname=public_user.username %}" {% if p == 'account' %}class="current-page"{% endif %}>Account</a></li>
    {% endif %}
    <li><a href="{% url account-places uname=public_user.username%}" {% if p == 'places' %}class="current-page"{% endif %}>Places</a></li>
    <li><a href="{% url account-events uname=public_user.username%}" {% if p == 'events' %}class="current-page"{% endif %}>Events</a></li>
    <li><a href="{% url account-specials uname=public_user.username%}" {% if p == 'specials' %}class="current-page"{% endif %}>Coupons</a></li>
</ul>

{% endwith %}

scenable/templates/accounts/page_profile.html
{% extends "page.html" %}
{% comment %}
Main outer template for user profile page

Context variables:
    public_user:    User object in question
    current_panel:  string
    account_forms:  collection of forms (available when current_panel is 'account')
    feed_items: collection of feed items (available when current_panel is a feed)
{% endcomment %}

{% block main-content %}
<article class="page-single detailed-single">
    {% include "accounts/public_profile.html" %}
    <nav id="profile-nav" class="detail-nav">
        {% include "accounts/nav_tabs.html" %}
    </nav>
    <section class="detail-section" id="profile">
        {% if current_panel == 'account' %}
        {% include "accounts/manage_account.html" %}
        {% endif %}
        
        {% if current_panel == 'places' %}
        {% include "accounts/places.html" with items=feed_items %}
        {% endif %}

        {% if current_panel == 'events' %}
        {% include "accounts/events.html" with items=feed_items %}
        {% endif %}

        {% if current_panel == 'specials' %}
        {% include "accounts/specials.html" with items=feed_items %}
        {% endif %}
    </section>
</article>
{% endblock %}

{% block sidebar %}
{% include "sidebar/sidebar_profile.html" %}
{% endblock %}

scenable/templates/accounts/places.html
{% comment %}
Inner template to render a list of places the user has favorited

Context variables:
    [feed_items]:  list of PlaceData instances
{% endcomment %}

<h2 class="detail-section-title">Favorite Places</h2>
{% if feed_items %}
	<ul class="feed my-feed places">
    	{% for item in feed_items %}
        	<li class="item">{% include "places/feed_item.html" with place=item %}</li>
    	{% endfor %}
	</ul>
{% else %}
	<section class="no-items">
    	<img src="{{STATIC_URL}}img/manage-place.png" alt="Store front" />
        {% if public_user == user %}
    	<p>Looks like you haven't favorited any places yet. Take a look through the Places page, click one you like and choose 'Favorite' under the places thumbnail picture. As Scenable develops, Scene Cred will be awarded based on your activity at favorited places.</p> 
        {% else %}
        <p>No favorited places here!</p>
        {% endif %}
    </section>
{% endif %}

scenable/templates/accounts/public_profile.html
{% comment %}
Template for user's public profile.

Context variables:
    public_user: User instance in question
{% endcomment %}
{% load thumbnail %}
{% with profile=public_user.get_profile %}
<header class="single-header">
    <div class="single-thumb-container">
        {% thumbnail profile.avatar "130x130" crop="center" as im %}
        <img class="thumbnail" alt="{{profile.display_name}}'s avatar" src="{{im.url}}" />
        {% empty %}
        <img class="thumbnail" alt="{{place.name|truncatewords:10}}" src="{{STATIC_URL}}img/defaults/default-avatar.png" />
        {% endthumbnail %}
    </div>
    <section class="item-content">
        <h1 class="single-title">{{ profile.display_or_username }}</h1>
        <ul class="item-details">
            <li>{{ profile.username }}</li>
            <li>{#{{ profile.points }}#}Scene Cred - <em>Coming soon!</em></li>
            {% if profile.neighborhood %}
            <li>{{ profile.neighborhood }}</li>
            {% endif %}
        </ul>
        <div class="social-container">
            {% comment %}
            {% if profile.fb_id %}
            <a href="http://www.facebook.com/{{ profile.fb_id }}"><img src="/static/img/icons/facebook.png" class="social-icon" alt="Facebook icon" /></a>
            {% endif %}
            {% endcomment %}
            {% if profile.twitter_username %}
            <a href="http://twitter.com/{{ profile.twitter_username }}" title="{{profile.display_name}}'s Twitter Account" target="blank"><img src="/static/img/icons/twitter.png" class="social-icon" alt="Twitter icon" /></a>
            {% endif %}        
        </div>
    </section>
</header>
{% endwith %}